/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package textEditor.views;

import java.awt.Component;
import static java.awt.SystemColor.text;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import textEditor.controller.PnltextEditorController;
import textEditor.panels.PnlTextEditor;

/**
 *
 * @author MateyR
 */
public class FrmTextEditor extends javax.swing.JFrame {

    private int countTab = 1;
    private PnlTextEditor pnltexteditor;
    
    /**
     * Creates new form FrmTextEditor
     */
    public FrmTextEditor() {
        initComponents();
    }
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        btnCloseTab = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        tbtContent = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniNew = new javax.swing.JMenuItem();
        mniBuscar = new javax.swing.JMenuItem();
        mniExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 420));

        jToolBar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        btnCloseTab.setText("Close");
        btnCloseTab.setBorder(new javax.swing.border.MatteBorder(null));
        btnCloseTab.setFocusable(false);
        btnCloseTab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCloseTab.setPreferredSize(new java.awt.Dimension(60, 30));
        btnCloseTab.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCloseTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseTabActionPerformed(evt);
            }
        });
        jToolBar2.add(btnCloseTab);

        btnSave.setText("Save");
        btnSave.setBorder(new javax.swing.border.MatteBorder(null));
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setPreferredSize(new java.awt.Dimension(60, 30));
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jToolBar2.add(btnSave);

        getContentPane().add(jToolBar2, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(tbtContent, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        mniNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new.png"))); // NOI18N
        mniNew.setText("Nuevo");
        mniNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNewActionPerformed(evt);
            }
        });
        jMenu1.add(mniNew);

        mniBuscar.setText("Buscar");
        mniBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBuscarActionPerformed(evt);
            }
        });
        jMenu1.add(mniBuscar);

        mniExit.setText("Exit");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        jMenu1.add(mniExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNewActionPerformed
      PnlTextEditor pnltexteditor =  new PnlTextEditor();
      tbtContent.addTab("Editor :" + countTab++, pnltexteditor);
      
      
    }//GEN-LAST:event_mniNewActionPerformed

    private void btnCloseTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseTabActionPerformed
        if(tbtContent.getComponentCount() <= 0){
            
            JOptionPane.showMessageDialog(this,"Caballo No hay ningun Editor abierto");
            return;
        } 
        int option = JOptionPane.showInternalConfirmDialog(null,"Are you sure to delete this tab",
                "Confirmation Dialog", JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        
        if(option == 1){
           return;
        }
        
        int index = tbtContent.getSelectedIndex();
        tbtContent.remove(index);
        
        
        
        
       
    }//GEN-LAST:event_btnCloseTabActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        pnltexteditor = (PnlTextEditor) tbtContent.getSelectedComponent();
        
        EscribeFichero(pnltexteditor);
       
        
        JOptionPane.showMessageDialog(this,"Guardado Papa");
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void mniBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBuscarActionPerformed
             
    }//GEN-LAST:event_mniBuscarActionPerformed

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniExitActionPerformed

    
    
       
 private void EscribeFichero(PnlTextEditor pnltexteditor){
        
       String texto = pnltexteditor.getTxtAEditor().getText();
       //"C:/Users/LENOVO/Documents/NetBeansProjects/TextEditor/Texto.txt"
       FileWriter flwriter = null;
		try {
                        String archivoname = JOptionPane.showInputDialog("Ingrese nombre con que desea guardar el archivo:");
			//crea el flujo para escribir en el archivo
			flwriter = new FileWriter("C:\\Users\\LENOVO\\Documents\\NetBeansProjects\\TextEditor\\src\\main\\resources\\Archivos\\"+ archivoname +".txt");  
			//crea un buffer o flujo intermedio antes de escribir directamente en el archivo
			BufferedWriter bfwriter = new BufferedWriter(flwriter);
                        
                        for (int i = 0; i <texto.length(); i++){
                            bfwriter.write(texto.charAt(i));
                        }
                        		
			//cierra el buffer intermedio
			bfwriter.close();
			
 
		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			if (flwriter != null) {
				try {//cierra el flujo principal
					flwriter.close();
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
		}
        
    }
 
  
 
 
 
 
 


    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTextEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTextEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTextEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTextEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTextEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseTab;
    private javax.swing.JButton btnSave;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JMenuItem mniBuscar;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniNew;
    private javax.swing.JTabbedPane tbtContent;
    // End of variables declaration//GEN-END:variables
}
