/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.programacion.views.panels;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author MateyR
 */
public class PnlConvertDin extends javax.swing.JPanel {

    /**
     * Creates new form PnlConvertDin
     */
    public PnlConvertDin() {
        initComponents();
    }

    public JButton getBtnConMo() {
        return btnConMo;
    }

    public void setBtnConMo(JButton btnConMo) {
        this.btnConMo = btnConMo;
    }

    public JLabel getBtnDolar() {
        return btnDolar;
    }

    public void setBtnDolar(JLabel btnDolar) {
        this.btnDolar = btnDolar;
    }

    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }

    public void setBtnLimpiar(JButton btnLimpiar) {
        this.btnLimpiar = btnLimpiar;
    }

    public JLabel getBtnResult() {
        return btnResult;
    }

    public void setBtnResult(JLabel btnResult) {
        this.btnResult = btnResult;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JTextField getTxtCordoba() {
        return txtCordoba;
    }

    public void setTxtCordoba(JTextField txtCordoba) {
        this.txtCordoba = txtCordoba;
    }

    public JTextField getTxtDolar() {
        return txtDolar;
    }

    public void setTxtDolar(JTextField txtDolar) {
        this.txtDolar = txtDolar;
    }

    public JTextField getTxtResultado() {
        return txtResultado;
    }

    public void setTxtResultado(JTextField txtResultado) {
        this.txtResultado = txtResultado;
    }

    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btnConMo = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnDolar = new javax.swing.JLabel();
        txtDolar = new javax.swing.JTextField();
        btnCorboda = new javax.swing.JLabel();
        txtCordoba = new javax.swing.JTextField();
        btnResult = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(300, 220));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnConMo.setText("Convertir");
        btnConMo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConMoActionPerformed(evt);
            }
        });
        jPanel1.add(btnConMo);

        btnLimpiar.setText("Liimpiar");
        jPanel1.add(btnLimpiar);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnDolar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDolar.setText("Dolar :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel2.add(btnDolar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel2.add(txtDolar, gridBagConstraints);

        btnCorboda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCorboda.setText("Cordoba :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel2.add(btnCorboda, gridBagConstraints);

        txtCordoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCordobaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel2.add(txtCordoba, gridBagConstraints);

        btnResult.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnResult.setText("Resultado :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel2.add(btnResult, gridBagConstraints);

        txtResultado.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel2.add(txtResultado, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCordobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCordobaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCordobaActionPerformed

    private void btnConMoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConMoActionPerformed
      
    }//GEN-LAST:event_btnConMoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConMo;
    private javax.swing.JLabel btnCorboda;
    private javax.swing.JLabel btnDolar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel btnResult;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCordoba;
    private javax.swing.JTextField txtDolar;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
