/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panel;

import Model.TableVehicleModel;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author MateyR
 */
public class PnlVehicleView extends javax.swing.JPanel {

    private TableVehicleModel TableVehicleModel; 
   
    public PnlVehicleView() throws FileNotFoundException {

        initComponents();
    }

    public PnlVehicleView(JPanel jPanel1, JPanel jPanel2, JScrollPane jScrollPane1, JTable tbVehicles, JTextField txtSearch) {
        
        this.jPanel1 = jPanel1;
        this.jPanel2 = jPanel2;
        this.jScrollPane1 = jScrollPane1;
        this.tbVehicles = tbVehicles;
        this.txtSearch = txtSearch;
    }

    public TableVehicleModel getTableVehicleModel() {
        return TableVehicleModel;
    }

    public void setTableVehicleModel(TableVehicleModel TableVehicleModel) {
        this.TableVehicleModel = TableVehicleModel;
        if(TableVehicleModel == null){
            return;
        }
        
        tbVehicles.setModel(TableVehicleModel);
    }

    
   

    public JTable getTbVehicles() {
        return tbVehicles;
    }
    

   


    public void setTbVehicles(JTable tbVehicles) {
        this.tbVehicles = tbVehicles;
    }

    public JTextField getTxtSearch() {
        return txtSearch;
    }

    public void setTxtSearch(JTextField txtSearch) {
        this.txtSearch = txtSearch;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVehicles = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(txtSearch, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));

        tbVehicles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbVehicles);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
      
    
    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
         String text = txtSearch.getText();
          Filter(text);
    }//GEN-LAST:event_txtSearchKeyReleased
         
    private void Filter(String text){   
        TableRowSorter<DefaultTableModel> tbSorter = new TableRowSorter<DefaultTableModel>((DefaultTableModel) tbVehicles.getModel());
        
        tbVehicles.setRowSorter(tbSorter);
        
        tbSorter.setRowFilter(RowFilter.regexFilter(text));
        
    }
    
                 
     
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbVehicles;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    
}
