package Pnl;

import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MateyR
 */
public class PnlPersonaInfo extends javax.swing.JPanel {

    /**
     * Creates new form PnlPersonaInfo
     */
    public PnlPersonaInfo() {
        initComponents();
    }

    public JLabel getLblCity() {
        return lblCity;
    }

    public JLabel getLblEdad() {
        return lblEdad;
    }

    public JLabel getLblName() {
        return lblName;
    }

    public JLabel getLblOcupacion() {
        return lblOcupacion;
    }

    public JLabel getLbllastName() {
        return lbllastName;
    }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lbllastName = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblOcupacion = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setPreferredSize(new java.awt.Dimension(400, 360));
        setLayout(new java.awt.GridLayout(5, 0));

        lblName.setText("Name :");
        add(lblName);

        lbllastName.setText("Last Name :");
        add(lbllastName);

        lblEdad.setText("Edad :");
        add(lblEdad);

        lblCity.setText("City :");
        add(lblCity);

        lblOcupacion.setText("Ocupacion :");
        add(lblOcupacion);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOcupacion;
    private javax.swing.JLabel lbllastName;
    // End of variables declaration//GEN-END:variables
}
